### ISSUE TITLE
LocalAudioFile function fails to load files

### ISSUE THREAD

**Issue by jmwenda** [echonest/remix#47]
When I add or use the LocalAudioFile("") function, and pass the file path parameter to the function, the following error is produced. Regardless of the file or the path, the error is always reproduced. This is the case on both Linux and Mac computers. Regardless of .wav or .mp3 files, the same error keeps popping up.

>>> audiofile = audio.LocalAudioFile('/tmp/tmp4e8cYC.wav')
['en-ffmpeg', '-i', '/tmp/tmp4e8cYC.wav', '-y', '-ac', '2', '-ar', '44100', '/tmp/tmphabAB8.wav']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/musicvenv/local/lib/python2.7/site-packages/echonest/remix/audio.py", line 944, in __init__
    sampleRate=sampleRate, numChannels=numChannels)
  File "/home/ubuntu/musicvenv/local/lib/python2.7/site-packages/echonest/remix/audio.py", line 403, in __init__
    self.load()
  File "/home/ubuntu/musicvenv/local/lib/python2.7/site-packages/echonest/remix/audio.py", line 421, in load
    numChannels=self.numChannels, sampleRate=self.sampleRate, verbose=self.verbose)
  File "/home/ubuntu/musicvenv/local/lib/python2.7/site-packages/echonest/remix/support/ffmpeg.py", line 88, in ffmpeg
    close_fds=(not win)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by SuzanaK** [comment]
I have the same problem.

**Comment by mikeperri** [comment]
Make sure you have ffmpeg installed and en-ffmpeg points to your ffmpeg installation.

I think this is the error you're supposed to see:
```en-ffmpeg not found! Please make sure ffmpeg is installed and create a link as follows:
    sudo ln -s `which ffmpeg` /usr/local/bin/en-ffmpeg
Alternatively, import echonest.remix.support.ffmpeg and modify ffmpeg.FFMPEG to name
the appropriate binary.```

That OSError is thrown whenever the [subprocess module](https://docs.python.org/2/library/subprocess.html) executes a process, but not in a shell, and it returns an error. You can test it like this:

```
>>> import subprocess
>>> subprocess.call("exit 1", shell=True)
1

>>> subprocess.call("exit 1", shell=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The stack trace shows an error at line 88 of [echonest/remix/support/ffmpeg.py](https://github.com/echonest/remix/blob/master/src/echonest/remix/support/ffmpeg.py#L80), after it called subprocess.Popen with shell=False to execute the ffmpeg command. So that explains why we just got the OSError and not the more helpful message.

The ffmpeg.py file has logic to handle different error messages thrown by the ffmpeg process, which is strange since it doesn't seem they would ever be executed. If you look at the blame on Github, the change from shell=False to shell=True was made in September 2014, a couple of years after the logic to handle the different ffmpeg errors was added. So this has probably been an issue since September 2014.

It sounds like using shell=True [is the way to go](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments). So we could leave that  but show a slightly more helpful error message by doing something like this in ffmpeg.py:
```
    try:
        p = subprocess.Popen(
                command,
                shell=False,
                stdin=(None if filename else subprocess.PIPE),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                close_fds=(not win)
        )
    except OSError:
        raise RuntimeError("Encountered an error while executing " + command)
```
We should also eliminate the code for parsing ffmpeg error output.
